"""
Data models for the predictive maintenance system.
Defines the core data structures used throughout the application.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class SensorData(BaseModel):
    """Sensor reading data point."""
    timestamp: datetime
    asset_id: str
    temperature: float
    vibration: float
    run_hours: float


class MaintenanceLog(BaseModel):
    """Maintenance log entry."""
    asset_id: str
    failure_type: str
    failure_date: datetime


class AssetBaseline(BaseModel):
    """Rolling baseline statistics for an asset."""
    asset_id: str
    window_days: int
    temperature_mean: float
    temperature_std: float
    vibration_mean: float
    vibration_std: float
    last_updated: datetime


class FailureAlert(BaseModel):
    """Failure alert generated by rule engine."""
    asset_id: str
    failure_mode: str
    severity: str  # LOW, MEDIUM, HIGH, CRITICAL
    confidence: float  # 0-1
    triggered_rules: List[str]
    timestamp: datetime


class RiskScore(BaseModel):
    """Risk assessment for an asset."""
    asset_id: str
    risk_score: float = Field(ge=0, le=100)
    failure_mode: str
    recommended_action: str
    severity_factors: Dict[str, float]  # severity, persistence, rate_of_change
    last_calculated: datetime


class RiskSummary(BaseModel):
    """Summary report of all asset risks."""
    assets: List[RiskScore]
    generated_at: datetime
    total_assets: int
    high_risk_count: int
    critical_risk_count: int


class UploadResponse(BaseModel):
    """Response for file upload endpoint."""
    message: str
    files_processed: int
    records_ingested: int
    errors: List[str]


# Asset types and their expected parameters
ASSET_TYPES = {
    "electric_motor": {
        "critical_temp_threshold": 80.0,  # Celsius
        "critical_vibration_threshold": 2.5,  # mm/s RMS
        "max_run_hours": 87600,  # 10 years in hours
    },
    "pump": {
        "critical_temp_threshold": 75.0,
        "critical_vibration_threshold": 2.0,
        "max_run_hours": 43800,  # 5 years in hours
    }
}

# Failure modes and their characteristics
FAILURE_MODES = {
    "Bearing Wear": {
        "primary_indicator": "vibration",
        "secondary_indicator": "temperature",
        "severity_multiplier": 1.0
    },
    "Overheating": {
        "primary_indicator": "temperature",
        "secondary_indicator": "run_hours",
        "severity_multiplier": 0.9
    },
    "Impending Failure": {
        "primary_indicator": "combined",
        "secondary_indicator": "trend",
        "severity_multiplier": 1.2
    },
    "Normal Operation": {
        "primary_indicator": "baseline",
        "secondary_indicator": "none",
        "severity_multiplier": 0.1
    }
}
